privacy added
Giom-fm/ff-eppendorf-website pull request #3
Opened 2023-09-07 10:27 UTC by alkock

Link zum index fehlt noch, müsste im Footer noch eingepflegt werden.

2023-09-07 10:44 UTC, Giom-fm commented
> Link zum index fehlt noch, müsste im Footer noch eingepflegt werden.

Could you add it? Have a look at [menus.de.toml](https://github.com/Giom-fm/ff-eppendorf-website/blob/a5e0dea44ae52ef83851d59ada905d81e1afd008/config/_default/menus/menus.de.toml#L72)

I would say in this order: Impressum, Datenschutz, Kontakt.

2023-09-07 12:42 UTC, alkock commented
I added the file to the config for the index. In the order above :)

2023-09-07 17:23 UTC, Giom-fm requested changes

2023-09-12 15:12 UTC, alkock commented on content/de/datenschutz.md
> +## Inhaltsübersicht
Removed the section entirely.

2023-09-12 15:13 UTC, alkock commented on content/de/datenschutz.md
> +### Verantwortlicher
Used the same format as in impressum.

2023-09-12 15:13 UTC, alkock commented on content/de/datenschutz.md
> +<a href="https://datenschutz-generator.de/">Erstellt mit kostenlosem Datenschutz-Generator.de von Dr. Thomas Schwenke</a>
Replaced with markdown-link

2023-09-22 12:14 UTC, Giom-fm commented
It seams that you deleted a lot of files. Did you rebased already?

2023-09-22 12:22 UTC, Giom-fm commented on content/de/datenschutz.md
> +<br>
There is one left ;)

2023-09-22 16:59 UTC, alkock commented on content/de/datenschutz.md
> +<br>
oops did a br fix :)

2023-09-22 17:00 UTC, alkock commented
> It seams that you deleted a lot of files. Did you rebased already?

Should be resolved, I see just two files [here](https://github.com/Giom-fm/ff-eppendorf-website/pull/3/files)

2023-09-24 17:01 UTC, Giom-fm approved these changes

2023-09-24 17:02 UTC, merged